name: dart_guava
description: Common libraries for dart based on Java's Guava library.
version: 1.0.0
repository: https://github.com/dorireuv/dart_guava

environment:
  sdk: ^3.2.6

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
